namespace SolaERP.Application.Entities.Order;

public class OrderCreateBidListDto
{
    public int BidMainId { get; set; }
    public string BidNo { get; set; }
    public int BidComparisonId { get; set; }
    public string ComparisonNo { get; set; }
    public int BidDetailId { get; set; }
    public int RFQDetailId { get; set; }
    public int LineNo { get; set; }
    public int RequestDetailId { get; set; }
    public int RequestMainId { get; set; }
    public string RequestNo { get; set; }
    public string RequestLine { get; set; }
    public string RequestUOM { get; set; }
    public string ItemCode { get; set; }
    public string ItemName { get; set; }
    public string ItemName2 { get; set; }
    public string UOM { get; set; }
    public bool AlternativeItem { get; set; }
    public string AlternativeItemCode { get; set; }
    public string AlternativeItemName { get; set; }
    public string PUOM { get; set; }
    public string AccountCode { get; set; }
    public string AccountName { get; set; }
    public decimal ConversionRate { get; set; }
    public string LineDescription { get; set; }
    public int Condition { get; set; }
    public decimal Quantity { get; set; }
    public int DiscountType { get; set; }
    public decimal DiscountValue { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal SingleUnitPrice { get; set; }
    public decimal TotalAmount { get; set; }
    public decimal DiscountedAmount { get; set; }
    public decimal ConvertedQTY { get; set; }
    public decimal ConvertedUnitPrice { get; set; }
    public int Status { get; set; }
    public int ApproveStatus { get; set; }
    public int AnalysisCode1Id { get; set; }
    public int AnalysisCode2Id { get; set; }
    public int AnalysisCode3Id { get; set; }
    public int AnalysisCode4Id { get; set; }
    public int AnalysisCode5Id { get; set; }
    public int AnalysisCode6Id { get; set; }
    public int AnalysisCode7Id { get; set; }
    public int AnalysisCode8Id { get; set; }
    public int AnalysisCode9Id { get; set; }
    public int AnalysisCode10Id { get; set; }
    public int CatId { get; set; }
    public string RFQNo { get; set; }
    public DateTime ComparisonDeadline { get; set; }
    public DateTime RequestedDate { get; set; }
    public string Priority { get; set; }
    public string RequestType { get; set; }
    public int RequestTypeId { get; set; }
    public string Location { get; set; }
    public string Warehouse { get; set; }
}