name: .NET

on:
  push:
    branches: [ "ErpBranch.E" ]
  pull_request:
    branches: [ "ErpBranch.E" ]

jobs:
  build:

    runs-on: sola

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: List Directory
      run: ls
