name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: sola

    steps:
    - name: Change Directory
      run: cd C:\Users\afiq.mehdizade\Desktop\projects\sola-erp-api
    - name: Start Deploy
      run: start start-deploy.cmd
